<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

	protected $touches = ['project'];

	protected $casts = [
		'completed' => 'boolean'
	];

	public function project () {
		return $this->belongsTo(Project::class);
	}

	public function path () {
		return "/projects/{$this->project->id}/tasks/{$this->id}";
	}

	public function complete () {
		$this->update(['completed' => true]);

		$this->recordActivity('completed_task');
	}

	public function incomplete () {
		$this->update(['completed' => false]);

		$this->recordActivity('incompleted_task');
	}

	public function activity () {
		return $this->morphMany(Activity::class, 'subject')->latest();
	}

	public function recordActivity ($description) {
		$this->activity()->create([
			'description' => $description,
			'project_id'  => $this->project->id,
		]);
	}

	//this is one way to do this, but this has been moved to an observer
//	protected static function boot () {
//
//		parent::boot(); // TODO: Change the autogenerated stub
//
//		static::created(function (Task $task) {
//			$task->project->recordActivity('created_task');
//		});
//
//		self::deleted(function (Task $task){
//			$task->project->recordActivity('deleted_task');
//		});
//
//	}

}
