<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Task extends Model {

	use RecordsActivity;

	/**
	 * Attributes to guard against mass assignment
	 * @var array
	 */
	protected $guarded = [];

	/**
	 * The relationships that should be touched on save
	 * @var array
	 */
	protected $touches = ['project'];

	/**
	 * Attributes that should be cast to native types
	 * @var array
	 */
	protected $casts = [
		'completed' => 'boolean'
	];

	/**
	 * Events that should trigger new activity
	 * @var array
	 */
	protected static $recordableEvents = ['created', 'deleted'];

	/**
	 * Get the owning project
	 * @return BelongsTo
	 */
	public function project () {
		return $this->belongsTo(Project::class);
	}

	/**
	 * Get the path to the Task
	 * @return string
	 */
	public function path () {
		return "/projects/{$this->project->id}/tasks/{$this->id}";
	}

	/**
	 * Mark the task as complete
	 */
	public function complete () {
		$this->update(['completed' => true]);

		$this->recordActivity('completed_task');
	}

	/**
	 * Mark the task as incomplete
	 */
	public function incomplete () {
		$this->update(['completed' => false]);

		$this->recordActivity('incompleted_task');
	}


	//this is one way to do this, but this has been moved to an observer
//	protected static function boot () {
//
//		parent::boot(); // TODO: Change the autogenerated stub
//
//		static::created(function (Task $task) {
//			$task->project->recordActivity('created_task');
//		});
//
//		self::deleted(function (Task $task){
//			$task->project->recordActivity('deleted_task');
//		});
//
//	}

}
